-- FarmaVida
-- Seeder: demo categories, brands, products and batches.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categories (name, slug, description, display_order, is_active) VALUES
('Medicamentos', 'medicamentos', 'Medicamentos com e sem prescricao, com regras de exibicao e venda.', 10, 1),
('Dermocosmeticos', 'dermocosmeticos', 'Cuidados com pele, cabelo e beleza.', 20, 1),
('Higiene e Bem-estar', 'higiene-bem-estar', 'Produtos de higiene pessoal e bem-estar.', 30, 1),
('Vitaminas e Suplementos', 'vitaminas-suplementos', 'Vitaminas, minerais e suplementos.', 40, 1),
('Termossensiveis', 'termossensiveis', 'Produtos que exigem controle de temperatura.', 50, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  display_order = VALUES(display_order),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO brands (name, slug, manufacturer_name, is_active) VALUES
('FarmaVida Genericos', 'farmavida-genericos', 'Fornecedor de demonstracao', 1),
('SaudeMax', 'saudemax', 'SaudeMax Laboratorios', 1),
('BioCare', 'biocare', 'BioCare Farma', 1),
('Dermaluz', 'dermaluz', 'Dermaluz Cosmeticos', 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  manufacturer_name = VALUES(manufacturer_name),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO products (
  public_id, category_id, brand_id, name, slug, internal_code, ean, sku,
  short_description, full_description, active_ingredient, dosage_form, presentation,
  anvisa_registration, registration_holder, sale_price, promotional_price, cost_price,
  profit_margin, current_stock, minimum_stock, maximum_stock, physical_location, aisle,
  shelf, drawer, sector, requires_prescription, prescription_type, remote_sale_policy,
  is_generic, is_thermosensitive, allows_delivery, allows_pickup, is_featured,
  is_active, visibility, search_keywords
) VALUES
(
  UUID(),
  (SELECT id FROM categories WHERE slug = 'medicamentos'),
  (SELECT id FROM brands WHERE slug = 'farmavida-genericos'),
  'Dipirona Sodica 500mg 10 Comprimidos',
  'dipirona-sodica-500mg-10-comprimidos',
  'MED-0001',
  '7890000000011',
  'MED-0001',
  'Analgesico e antitermico de venda livre.',
  'Produto demonstrativo para catalogo FarmaVida. Informacoes devem ser revisadas por responsavel tecnico antes de uso real.',
  'Dipirona sodica',
  'Comprimido',
  '500mg com 10 comprimidos',
  'MS-0000000001',
  'FarmaVida Genericos',
  12.90,
  10.90,
  6.20,
  48.00,
  120,
  15,
  300,
  'Corredor A - Prateleira 1',
  'A',
  '1',
  'G1',
  'Medicamentos',
  0,
  'none',
  'allowed',
  1,
  0,
  1,
  1,
  1,
  1,
  'public',
  'dor febre analgesico antitermico dipirona'
),
(
  UUID(),
  (SELECT id FROM categories WHERE slug = 'medicamentos'),
  (SELECT id FROM brands WHERE slug = 'saudemax'),
  'Amoxicilina 500mg 21 Capsulas',
  'amoxicilina-500mg-21-capsulas',
  'MED-0002',
  '7890000000028',
  'MED-0002',
  'Antibiotico com venda condicionada a receita.',
  'Produto demonstrativo. Antibioticos exigem receita e validacao farmaceutica antes da liberacao.',
  'Amoxicilina',
  'Capsula',
  '500mg com 21 capsulas',
  'MS-0000000002',
  'SaudeMax Laboratorios',
  39.90,
  NULL,
  21.00,
  47.37,
  60,
  10,
  180,
  'Corredor B - Prateleira 2',
  'B',
  '2',
  'G2',
  'Medicamentos',
  1,
  'antibiotic',
  'requires_pharmacist_validation',
  0,
  0,
  1,
  1,
  0,
  1,
  'restricted',
  'antibiotico amoxicilina infeccao receita'
),
(
  UUID(),
  (SELECT id FROM categories WHERE slug = 'medicamentos'),
  (SELECT id FROM brands WHERE slug = 'biocare'),
  'Clonazepam 2mg 30 Comprimidos',
  'clonazepam-2mg-30-comprimidos',
  'MED-0003',
  '7890000000035',
  'MED-0003',
  'Medicamento controlado. Venda remota automatica bloqueada.',
  'Produto demonstrativo de controle especial. O fluxo deve bloquear compra automatica e direcionar para orientacao farmaceutica/retirada conforme configuracao legal.',
  'Clonazepam',
  'Comprimido',
  '2mg com 30 comprimidos',
  'MS-0000000003',
  'BioCare Farma',
  24.90,
  NULL,
  12.00,
  51.81,
  20,
  5,
  80,
  'Armario Controlados - Gaveta C1',
  'Controlados',
  '1',
  'C1',
  'Controlados',
  1,
  'controlled',
  'blocked',
  0,
  0,
  0,
  1,
  0,
  1,
  'restricted',
  'controlado clonazepam psicotropico receita especial'
),
(
  UUID(),
  (SELECT id FROM categories WHERE slug = 'termossensiveis'),
  (SELECT id FROM brands WHERE slug = 'biocare'),
  'Insulina NPH 100UI/mL 10mL',
  'insulina-nph-100ui-ml-10ml',
  'TER-0001',
  '7890000000042',
  'TER-0001',
  'Produto termossensivel com controle de temperatura.',
  'Produto demonstrativo. Entrega deve considerar cadeia fria e janela operacional.',
  'Insulina humana NPH',
  'Suspensao injetavel',
  '100UI/mL frasco 10mL',
  'MS-0000000004',
  'BioCare Farma',
  84.90,
  NULL,
  56.00,
  34.04,
  30,
  6,
  90,
  'Geladeira 2 - Bandeja A',
  'Frio',
  '2',
  'A',
  'Termossensiveis',
  1,
  'simple',
  'requires_pharmacist_validation',
  0,
  1,
  1,
  1,
  0,
  1,
  'restricted',
  'insulina diabetes termossensivel cadeia fria'
),
(
  UUID(),
  (SELECT id FROM categories WHERE slug = 'dermocosmeticos'),
  (SELECT id FROM brands WHERE slug = 'dermaluz'),
  'Protetor Solar FPS 50 120mL',
  'protetor-solar-fps-50-120ml',
  'DER-0001',
  '7890000000059',
  'DER-0001',
  'Protetor solar facial e corporal.',
  'Produto demonstrativo de dermocosmetico para venda livre.',
  NULL,
  'Loção',
  'FPS 50 120mL',
  NULL,
  'Dermaluz Cosmeticos',
  59.90,
  49.90,
  31.50,
  47.41,
  75,
  12,
  200,
  'Corredor C - Prateleira 3',
  'C',
  '3',
  'D1',
  'Dermocosmeticos',
  0,
  'none',
  'allowed',
  0,
  0,
  1,
  1,
  1,
  1,
  'public',
  'protetor solar fps pele sol'
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  sale_price = VALUES(sale_price),
  promotional_price = VALUES(promotional_price),
  current_stock = VALUES(current_stock),
  minimum_stock = VALUES(minimum_stock),
  requires_prescription = VALUES(requires_prescription),
  prescription_type = VALUES(prescription_type),
  remote_sale_policy = VALUES(remote_sale_policy),
  is_thermosensitive = VALUES(is_thermosensitive),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO product_batches (product_id, batch_code, supplier_name, manufacture_date, expiration_date, purchase_price, stock_quantity, storage_location, status)
SELECT id, CONCAT('LT-', internal_code, '-A'), 'Fornecedor demonstrativo', DATE_SUB(CURRENT_DATE, INTERVAL 2 MONTH), DATE_ADD(CURRENT_DATE, INTERVAL 18 MONTH), cost_price, current_stock, physical_location, 'available'
FROM products
WHERE internal_code IN ('MED-0001','MED-0002','MED-0003','TER-0001','DER-0001')
ON DUPLICATE KEY UPDATE
  stock_quantity = VALUES(stock_quantity),
  expiration_date = VALUES(expiration_date),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO stock_movements (public_id, product_id, batch_id, movement_type, reason, previous_quantity, movement_quantity, final_quantity, new_location, unit_cost, total_cost, reference_type, responsible_user_id)
SELECT UUID(), p.id, pb.id, 'entrada_compra', 'Carga inicial de demonstracao', 0, p.current_stock, p.current_stock, p.physical_location, p.cost_price, p.cost_price * p.current_stock, 'seed', NULL
FROM products p
INNER JOIN product_batches pb ON pb.product_id = p.id AND pb.batch_code = CONCAT('LT-', p.internal_code, '-A')
WHERE p.internal_code IN ('MED-0001','MED-0002','MED-0003','TER-0001','DER-0001')
  AND NOT EXISTS (
    SELECT 1
    FROM stock_movements sm
    WHERE sm.product_id = p.id
      AND sm.reference_type = 'seed'
      AND sm.reason = 'Carga inicial de demonstracao'
  );
