-- FarmaVida
-- Module: categorias + produtos
-- Purpose: catalog, pharmaceutical metadata, images, kits, recommendations, batches and expiration control.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  parent_id BIGINT UNSIGNED NULL,
  name VARCHAR(140) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  description TEXT NULL,
  image_path VARCHAR(255) NULL,
  banner_path VARCHAR(255) NULL,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  seo_title VARCHAR(190) NULL,
  seo_description VARCHAR(255) NULL,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_categories_slug (slug),
  KEY idx_categories_parent_active (parent_id, is_active),
  KEY idx_categories_deleted_at (deleted_at),
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS brands (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(140) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  manufacturer_name VARCHAR(180) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_brands_slug (slug),
  KEY idx_brands_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  category_id BIGINT UNSIGNED NULL,
  brand_id BIGINT UNSIGNED NULL,
  generic_product_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(210) NOT NULL,
  internal_code VARCHAR(80) NOT NULL,
  ean VARCHAR(30) NULL,
  sku VARCHAR(80) NULL,
  short_description VARCHAR(500) NULL,
  full_description MEDIUMTEXT NULL,
  active_ingredient VARCHAR(190) NULL,
  dosage_form VARCHAR(120) NULL,
  presentation VARCHAR(190) NULL,
  anvisa_registration VARCHAR(80) NULL,
  registration_holder VARCHAR(190) NULL,
  sale_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  promotional_price DECIMAL(12,2) NULL,
  promotional_starts_at DATETIME NULL,
  promotional_ends_at DATETIME NULL,
  cost_price DECIMAL(12,2) NULL,
  profit_margin DECIMAL(6,2) NULL,
  current_stock INT NOT NULL DEFAULT 0,
  minimum_stock INT NOT NULL DEFAULT 0,
  maximum_stock INT NULL,
  physical_location VARCHAR(160) NULL,
  aisle VARCHAR(60) NULL,
  shelf VARCHAR(60) NULL,
  drawer VARCHAR(60) NULL,
  sector VARCHAR(80) NULL,
  main_image_path VARCHAR(255) NULL,
  requires_prescription TINYINT(1) NOT NULL DEFAULT 0,
  prescription_type ENUM('none','simple','antibiotic','controlled','psychotropic') NOT NULL DEFAULT 'none',
  remote_sale_policy ENUM('allowed','requires_prescription','requires_pharmacist_validation','reservation_only','pickup_only','blocked') NOT NULL DEFAULT 'allowed',
  is_generic TINYINT(1) NOT NULL DEFAULT 0,
  is_thermosensitive TINYINT(1) NOT NULL DEFAULT 0,
  temperature_min_c DECIMAL(5,2) NULL,
  temperature_max_c DECIMAL(5,2) NULL,
  allows_delivery TINYINT(1) NOT NULL DEFAULT 1,
  allows_pickup TINYINT(1) NOT NULL DEFAULT 1,
  allow_pre_sale TINYINT(1) NOT NULL DEFAULT 0,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  visibility ENUM('public','restricted','admin_only') NOT NULL DEFAULT 'public',
  seo_title VARCHAR(190) NULL,
  seo_description VARCHAR(255) NULL,
  search_keywords TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_public_id (public_id),
  UNIQUE KEY uq_products_slug (slug),
  UNIQUE KEY uq_products_internal_code (internal_code),
  UNIQUE KEY uq_products_ean (ean),
  KEY idx_products_category_active (category_id, is_active),
  KEY idx_products_brand_active (brand_id, is_active),
  KEY idx_products_generic_product_id (generic_product_id),
  KEY idx_products_name (name),
  KEY idx_products_active_ingredient (active_ingredient),
  KEY idx_products_prescription (requires_prescription, prescription_type),
  KEY idx_products_stock (current_stock, minimum_stock),
  KEY idx_products_price (sale_price),
  KEY idx_products_deleted_at (deleted_at),
  KEY idx_products_created_by (created_by),
  KEY idx_products_updated_by (updated_by),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL,
  CONSTRAINT fk_products_generic FOREIGN KEY (generic_product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_products_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE FULLTEXT INDEX ft_products_search ON products (name, active_ingredient, search_keywords);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  storage_path VARCHAR(255) NOT NULL,
  original_name VARCHAR(190) NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size INT UNSIGNED NOT NULL,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  alt_text VARCHAR(190) NULL,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_main TINYINT(1) NOT NULL DEFAULT 0,
  uploaded_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_product_images_product_order (product_id, display_order),
  KEY idx_product_images_uploaded_by (uploaded_by),
  KEY idx_product_images_deleted_at (deleted_at),
  CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_images_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_recommendations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  recommended_product_id BIGINT UNSIGNED NOT NULL,
  recommendation_type ENUM('generic','similar','related','cross_sell','up_sell','replacement') NOT NULL,
  priority SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_product_recommendations_pair_type (product_id, recommended_product_id, recommendation_type),
  KEY idx_product_recommendations_recommended (recommended_product_id),
  KEY idx_product_recommendations_type_active (recommendation_type, is_active),
  CONSTRAINT fk_product_recommendations_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_recommendations_recommended FOREIGN KEY (recommended_product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_kits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(210) NOT NULL,
  description TEXT NULL,
  kit_price DECIMAL(12,2) NULL,
  discount_type ENUM('none','fixed','percent') NOT NULL DEFAULT 'none',
  discount_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_product_kits_slug (slug),
  KEY idx_product_kits_active_dates (is_active, starts_at, ends_at),
  KEY idx_product_kits_created_by (created_by),
  KEY idx_product_kits_updated_by (updated_by),
  KEY idx_product_kits_deleted_at (deleted_at),
  CONSTRAINT fk_product_kits_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_product_kits_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_kit_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  kit_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_product_kit_items_kit_product (kit_id, product_id),
  KEY idx_product_kit_items_product (product_id),
  CONSTRAINT fk_product_kit_items_kit FOREIGN KEY (kit_id) REFERENCES product_kits(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_kit_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  batch_code VARCHAR(100) NOT NULL,
  supplier_name VARCHAR(160) NULL,
  manufacture_date DATE NULL,
  expiration_date DATE NOT NULL,
  purchase_price DECIMAL(12,2) NULL,
  stock_quantity INT NOT NULL DEFAULT 0,
  reserved_quantity INT NOT NULL DEFAULT 0,
  blocked_quantity INT NOT NULL DEFAULT 0,
  storage_location VARCHAR(160) NULL,
  temperature_checked TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('available','reserved','blocked','expired','recalled','depleted') NOT NULL DEFAULT 'available',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_product_batches_product_batch (product_id, batch_code),
  KEY idx_product_batches_expiration (expiration_date, status),
  KEY idx_product_batches_product_status (product_id, status),
  KEY idx_product_batches_created_by (created_by),
  KEY idx_product_batches_updated_by (updated_by),
  CONSTRAINT fk_product_batches_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_batches_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_product_batches_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_expirations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NULL,
  expiration_date DATE NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  alert_level ENUM('normal','attention','critical','expired') NOT NULL DEFAULT 'normal',
  notified_at DATETIME NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_product_expirations_product_date (product_id, expiration_date),
  KEY idx_product_expirations_batch (batch_id),
  KEY idx_product_expirations_alert (alert_level, resolved_at),
  CONSTRAINT fk_product_expirations_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_expirations_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_price_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  old_sale_price DECIMAL(12,2) NULL,
  new_sale_price DECIMAL(12,2) NOT NULL,
  old_promotional_price DECIMAL(12,2) NULL,
  new_promotional_price DECIMAL(12,2) NULL,
  reason VARCHAR(255) NULL,
  changed_by BIGINT UNSIGNED NULL,
  changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_product_price_history_product_changed (product_id, changed_at),
  KEY idx_product_price_history_changed_by (changed_by),
  CONSTRAINT fk_product_price_history_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_price_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

