-- FarmaVida
-- Module: pedidos
-- Purpose: carts, abandoned carts, orders, order items and status timeline.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS carts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  session_id_hash CHAR(64) NULL,
  share_token_hash CHAR(64) NULL,
  status ENUM('active','converted','abandoned','expired','cancelled') NOT NULL DEFAULT 'active',
  currency CHAR(3) NOT NULL DEFAULT 'BRL',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  delivery_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  grand_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  coupon_code VARCHAR(80) NULL,
  expires_at DATETIME NULL,
  last_activity_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  converted_order_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_carts_public_id (public_id),
  UNIQUE KEY uq_carts_share_token_hash (share_token_hash),
  KEY idx_carts_customer_status (customer_id, status),
  KEY idx_carts_session_status (session_id_hash, status),
  KEY idx_carts_expires_status (expires_at, status),
  KEY idx_carts_converted_order_id (converted_order_id),
  CONSTRAINT fk_carts_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  promotional_unit_price DECIMAL(12,2) NULL,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  requires_prescription TINYINT(1) NOT NULL DEFAULT 0,
  prescription_type ENUM('none','simple','antibiotic','controlled','psychotropic') NOT NULL DEFAULT 'none',
  added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cart_items_cart_product_batch (cart_id, product_id, batch_id),
  KEY idx_cart_items_product_id (product_id),
  KEY idx_cart_items_batch_id (batch_id),
  CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cart_items_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS abandoned_carts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  recovery_token_hash CHAR(64) NOT NULL,
  email VARCHAR(190) NULL,
  status ENUM('pending','email_sent','recovered','expired','cancelled') NOT NULL DEFAULT 'pending',
  first_detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_email_sent_at DATETIME NULL,
  recovered_at DATETIME NULL,
  expires_at DATETIME NOT NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_abandoned_carts_cart_id (cart_id),
  UNIQUE KEY uq_abandoned_carts_recovery_token_hash (recovery_token_hash),
  KEY idx_abandoned_carts_customer_status (customer_id, status),
  KEY idx_abandoned_carts_status_expires (status, expires_at),
  CONSTRAINT fk_abandoned_carts_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
  CONSTRAINT fk_abandoned_carts_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_number VARCHAR(40) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  cart_id BIGINT UNSIGNED NULL,
  customer_address_id BIGINT UNSIGNED NULL,
  responsible_user_id BIGINT UNSIGNED NULL,
  status ENUM('pedido_recebido','aguardando_pagamento','pagamento_em_analise','pagamento_confirmado','aguardando_receita','receita_enviada','receita_em_validacao','receita_aprovada','receita_rejeitada','liberado_pelo_farmaceutico','em_separacao','conferido','saiu_para_entrega','pronto_para_retirada','entregue','cancelado') NOT NULL DEFAULT 'pedido_recebido',
  payment_status ENUM('aguardando_pagamento','em_analise','aprovado','recusado','cancelado','estornado','expirado','divergente') NOT NULL DEFAULT 'aguardando_pagamento',
  clinical_status ENUM('nao_exige_receita','aguardando_receita','receita_enviada','em_validacao','liberado','rejeitado','bloqueado_orientacao_farmaceutica') NOT NULL DEFAULT 'nao_exige_receita',
  delivery_method ENUM('pickup','local_delivery','motoboy','carrier') NOT NULL DEFAULT 'pickup',
  delivery_status ENUM('not_required','pending','assigned','in_transit','delivered','failed','returned') NOT NULL DEFAULT 'pending',
  priority ENUM('normal','urgent','critical') NOT NULL DEFAULT 'normal',
  has_problem TINYINT(1) NOT NULL DEFAULT 0,
  problem_reason VARCHAR(255) NULL,
  requires_prescription TINYINT(1) NOT NULL DEFAULT 0,
  has_controlled_items TINYINT(1) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'BRL',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  coupon_discount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  delivery_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  grand_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  cost_total DECIMAL(12,2) NULL,
  estimated_profit DECIMAL(12,2) NULL,
  coupon_code VARCHAR(80) NULL,
  customer_note TEXT NULL,
  internal_note TEXT NULL,
  pharmacy_note_to_customer TEXT NULL,
  delivery_address_snapshot JSON NULL,
  customer_snapshot JSON NULL,
  estimated_delivery_at DATETIME NULL,
  paid_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(255) NULL,
  delivered_at DATETIME NULL,
  created_ip VARCHAR(45) NULL,
  created_user_agent VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_public_id (public_id),
  UNIQUE KEY uq_orders_order_number (order_number),
  KEY idx_orders_customer_created (customer_id, created_at),
  KEY idx_orders_cart_id (cart_id),
  KEY idx_orders_address_id (customer_address_id),
  KEY idx_orders_status_created (status, created_at),
  KEY idx_orders_payment_status (payment_status),
  KEY idx_orders_clinical_status (clinical_status),
  KEY idx_orders_delivery_method_status (delivery_method, delivery_status),
  KEY idx_orders_responsible_status (responsible_user_id, status),
  KEY idx_orders_priority_problem (priority, has_problem),
  KEY idx_orders_deleted_at (deleted_at),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_address FOREIGN KEY (customer_address_id) REFERENCES customer_addresses(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_responsible FOREIGN KEY (responsible_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  batch_id BIGINT UNSIGNED NULL,
  product_name VARCHAR(190) NOT NULL,
  product_sku VARCHAR(80) NULL,
  ean VARCHAR(30) NULL,
  active_ingredient VARCHAR(190) NULL,
  anvisa_registration VARCHAR(80) NULL,
  quantity INT UNSIGNED NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  promotional_unit_price DECIMAL(12,2) NULL,
  discount_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(12,2) NOT NULL,
  cost_unit_price DECIMAL(12,2) NULL,
  requires_prescription TINYINT(1) NOT NULL DEFAULT 0,
  prescription_type ENUM('none','simple','antibiotic','controlled','psychotropic') NOT NULL DEFAULT 'none',
  is_controlled TINYINT(1) NOT NULL DEFAULT 0,
  is_thermosensitive TINYINT(1) NOT NULL DEFAULT 0,
  product_snapshot JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_order_items_order_id (order_id),
  KEY idx_order_items_product_id (product_id),
  KEY idx_order_items_batch_id (batch_id),
  KEY idx_order_items_prescription (requires_prescription, prescription_type),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT fk_order_items_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE carts
  ADD CONSTRAINT fk_carts_converted_order FOREIGN KEY (converted_order_id) REFERENCES orders(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS order_status_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  previous_status VARCHAR(80) NULL,
  new_status VARCHAR(80) NOT NULL,
  previous_payment_status VARCHAR(80) NULL,
  new_payment_status VARCHAR(80) NULL,
  previous_clinical_status VARCHAR(80) NULL,
  new_clinical_status VARCHAR(80) NULL,
  visible_to_customer TINYINT(1) NOT NULL DEFAULT 1,
  message_to_customer VARCHAR(500) NULL,
  internal_note TEXT NULL,
  changed_by BIGINT UNSIGNED NULL,
  source ENUM('customer','admin','system','payment_webhook','api','erp') NOT NULL DEFAULT 'admin',
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_order_status_history_order_created (order_id, created_at),
  KEY idx_order_status_history_changed_by (changed_by),
  KEY idx_order_status_history_new_status (new_status),
  CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_status_history_changed_by FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

