-- FarmaVida
-- Module: pagamentos
-- Purpose: Mercado Pago payments, idempotency, webhooks and reconciliation.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  provider ENUM('mercado_pago','manual','sandbox_fake') NOT NULL DEFAULT 'mercado_pago',
  environment ENUM('sandbox','production') NOT NULL DEFAULT 'sandbox',
  payment_method ENUM('pix','credit_card','debit_card','boleto','manual','unknown') NOT NULL DEFAULT 'unknown',
  provider_payment_id VARCHAR(120) NULL,
  provider_preference_id VARCHAR(120) NULL,
  idempotency_key_hash CHAR(64) NOT NULL,
  status ENUM('aguardando_pagamento','em_analise','aprovado','recusado','cancelado','estornado','expirado','divergente') NOT NULL DEFAULT 'aguardando_pagamento',
  provider_status VARCHAR(80) NULL,
  provider_status_detail VARCHAR(160) NULL,
  installments SMALLINT UNSIGNED NULL,
  amount DECIMAL(12,2) NOT NULL,
  refunded_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  currency CHAR(3) NOT NULL DEFAULT 'BRL',
  payer_email VARCHAR(190) NULL,
  payer_document_masked VARCHAR(30) NULL,
  pix_qr_code TEXT NULL,
  pix_qr_code_base64 MEDIUMTEXT NULL,
  pix_expiration_at DATETIME NULL,
  checkout_url VARCHAR(500) NULL,
  metadata JSON NULL,
  approved_at DATETIME NULL,
  paid_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  expires_at DATETIME NULL,
  last_synced_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payments_public_id (public_id),
  UNIQUE KEY uq_payments_idempotency_key_hash (idempotency_key_hash),
  UNIQUE KEY uq_payments_provider_payment (provider, provider_payment_id),
  KEY idx_payments_order_status (order_id, status),
  KEY idx_payments_provider_status (provider, provider_status),
  KEY idx_payments_environment_created (environment, created_at),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_webhooks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider ENUM('mercado_pago','manual','other') NOT NULL DEFAULT 'mercado_pago',
  environment ENUM('sandbox','production') NOT NULL DEFAULT 'sandbox',
  event_id VARCHAR(190) NULL,
  payment_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  topic VARCHAR(120) NULL,
  action VARCHAR(120) NULL,
  signature_header VARCHAR(500) NULL,
  signature_valid TINYINT(1) NOT NULL DEFAULT 0,
  request_id VARCHAR(190) NULL,
  idempotency_key_hash CHAR(64) NULL,
  headers_json JSON NULL,
  payload_json JSON NULL,
  sanitized_payload_json JSON NULL,
  processing_status ENUM('received','ignored','processed','failed','duplicate') NOT NULL DEFAULT 'received',
  error_message TEXT NULL,
  received_ip VARCHAR(45) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_webhooks_provider_event (provider, event_id),
  KEY idx_payment_webhooks_payment (payment_id),
  KEY idx_payment_webhooks_order (order_id),
  KEY idx_payment_webhooks_status_received (processing_status, received_at),
  KEY idx_payment_webhooks_signature_valid (signature_valid),
  CONSTRAINT fk_payment_webhooks_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
  CONSTRAINT fk_payment_webhooks_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_refunds (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_id BIGINT UNSIGNED NOT NULL,
  provider_refund_id VARCHAR(120) NULL,
  amount DECIMAL(12,2) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status ENUM('requested','approved','rejected','cancelled','failed') NOT NULL DEFAULT 'requested',
  requested_by BIGINT UNSIGNED NULL,
  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME NULL,
  provider_payload JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_refunds_provider_refund (provider_refund_id),
  KEY idx_payment_refunds_payment_status (payment_id, status),
  KEY idx_payment_refunds_requested_by (requested_by),
  CONSTRAINT fk_payment_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_refunds_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_reconciliations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  provider ENUM('mercado_pago','manual','other') NOT NULL DEFAULT 'mercado_pago',
  provider_payment_id VARCHAR(120) NULL,
  expected_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  provider_amount DECIMAL(12,2) NULL,
  expected_status VARCHAR(80) NULL,
  provider_status VARCHAR(80) NULL,
  status ENUM('matched','amount_mismatch','status_mismatch','missing_order','missing_payment','manual_review','resolved') NOT NULL DEFAULT 'manual_review',
  notes TEXT NULL,
  resolved_by BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_payment_reconciliations_payment (payment_id),
  KEY idx_payment_reconciliations_order (order_id),
  KEY idx_payment_reconciliations_status (status),
  KEY idx_payment_reconciliations_provider_payment (provider, provider_payment_id),
  KEY idx_payment_reconciliations_resolved_by (resolved_by),
  CONSTRAINT fk_payment_reconciliations_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
  CONSTRAINT fk_payment_reconciliations_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_payment_reconciliations_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

