import { adaptAction } from "@/client/api/result";
import { invalidateCatalog } from "@/client/api/cache";
import * as coupons from "@/actions/admin/coupons";
import * as deliveries from "@/actions/admin/deliveries";
import * as finance from "@/actions/admin/finance";
import * as inventory from "@/actions/admin/inventory";
import * as lots from "@/actions/admin/inventory-lots";
import * as orders from "@/actions/admin/orders";
import * as payments from "@/actions/admin/payments";
import * as pharmacies from "@/actions/admin/pharmacies";
import * as productImport from "@/actions/admin/product-import";
import * as products from "@/actions/admin/products";
import * as purchasing from "@/actions/admin/purchasing";
import * as reviews from "@/actions/admin/reviews";
import * as settings from "@/actions/admin/settings";
import * as team from "@/actions/admin/team";

export { createProduct, updateProduct, createCoupon, updateCoupon, saveSettings } from "@/client/api/form-actions";
export { getPendingOrders } from "@/client/api/orders";
export { decideReturnRequest, receiveReturnRequest, decideReturnItemDisposition, retryReturnRefund } from "@/client/api/account";
export type { FormState as CouponFormState, FormState as SettingsFormState, FormState as ProductFormState } from "@/contracts/result";
export type { ImportResult, ImportStatementResult, UnitOfferValues, LotActionResult, PaymentActionResult, PharmacyResult, TeamResult } from "@/contracts/forms";

export const toggleCoupon = adaptAction(coupons.toggleCoupon, { invalidate: invalidateCatalog });
export const deleteCoupon = adaptAction(coupons.deleteCoupon, { invalidate: invalidateCatalog });
export const createCourier = adaptAction(deliveries.createCourier, { invalidate: invalidateCatalog });
export const toggleCourier = adaptAction(deliveries.toggleCourier, { invalidate: invalidateCatalog });
export const dispatchOrder = adaptAction(deliveries.dispatchOrder, { invalidate: invalidateCatalog });
export const markDelivered = adaptAction(deliveries.markDelivered, { invalidate: invalidateCatalog });
export const createExpense = adaptAction(finance.createExpense, { invalidate: invalidateCatalog });
export const deleteExpense = adaptAction(finance.deleteExpense, { invalidate: invalidateCatalog });
export const importStatement = adaptAction(finance.importStatement, { invalidate: invalidateCatalog, failureDefaults: { imported: 0, duplicated: 0, matched: 0 } });
export const updateUnitOffer = adaptAction(inventory.updateUnitOffer, { invalidate: invalidateCatalog });
export const adjustStock = adaptAction(inventory.adjustStock, { invalidate: invalidateCatalog });
export const transferStock = adaptAction(inventory.transferStock, { invalidate: invalidateCatalog });
export const receiveInventoryLot = adaptAction(lots.receiveInventoryLot, { invalidate: invalidateCatalog });
export const writeOffInventoryLot = adaptAction(lots.writeOffInventoryLot, { invalidate: invalidateCatalog });
export const updateOrderStatus = adaptAction(orders.updateOrderStatus, { invalidate: invalidateCatalog });
export const retryOrderRefund = adaptAction(orders.retryOrderRefund, { invalidate: invalidateCatalog });
export const transferOrderToUnit = adaptAction(orders.transferOrderToUnit, { invalidate: invalidateCatalog });
export const archiveOrder = adaptAction(orders.archiveOrder, { invalidate: invalidateCatalog });
export const restoreOrder = adaptAction(orders.restoreOrder, { invalidate: invalidateCatalog });
export const saveOrderNotes = adaptAction(orders.saveOrderNotes, { invalidate: invalidateCatalog });
export const recheckQuarantinedPayment = adaptAction(payments.recheckQuarantinedPayment, { invalidate: invalidateCatalog });
export const refundQuarantinedPayment = adaptAction(payments.refundQuarantinedPayment, { invalidate: invalidateCatalog });
export const createPharmacy = adaptAction(pharmacies.createPharmacy, { invalidate: invalidateCatalog });
export const setPharmacyActive = adaptAction(pharmacies.setPharmacyActive, { invalidate: invalidateCatalog });
export const archivePharmacy = adaptAction(pharmacies.archivePharmacy, { invalidate: invalidateCatalog });
export const restorePharmacy = adaptAction(pharmacies.restorePharmacy, { invalidate: invalidateCatalog });
export const addCepRange = adaptAction(pharmacies.addCepRange, { invalidate: invalidateCatalog });
export const removeCepRange = adaptAction(pharmacies.removeCepRange, { invalidate: invalidateCatalog });
export const setPharmacyShipping = adaptAction(pharmacies.setPharmacyShipping, { invalidate: invalidateCatalog });
export const setPharmacyRegulatory = adaptAction(pharmacies.setPharmacyRegulatory, { invalidate: invalidateCatalog });
export const assignUnitAdmin = adaptAction(pharmacies.assignUnitAdmin, { invalidate: invalidateCatalog });
export const removeUnitAdmin = adaptAction(pharmacies.removeUnitAdmin, { invalidate: invalidateCatalog });
export const importProducts = adaptAction(productImport.importProducts, { invalidate: invalidateCatalog, failureDefaults: { created: 0, updated: 0, errors: ["Não foi possível confirmar a importação. Atualize a página antes de tentar novamente."] } });
export const toggleProductActive = adaptAction(products.toggleProductActive, { invalidate: invalidateCatalog });
export const deleteProduct = adaptAction(products.deleteProduct, { invalidate: invalidateCatalog });
export const setStockLevels = adaptAction(purchasing.setStockLevels, { invalidate: invalidateCatalog });
export const approveReview = adaptAction(reviews.approveReview, { invalidate: invalidateCatalog });
export const rejectReview = adaptAction(reviews.rejectReview, { invalidate: invalidateCatalog });
export const testStripeConnection = adaptAction(settings.testStripeConnection, { invalidate: invalidateCatalog });
export const createStaff = adaptAction(team.createStaff, { invalidate: invalidateCatalog });
export const updateStaffProfile = adaptAction(team.updateStaffProfile, { invalidate: invalidateCatalog });
export const revokeStaff = adaptAction(team.revokeStaff, { invalidate: invalidateCatalog });
